-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email character varying,
    password character varying,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id character varying NOT NULL,
    role_id character varying NOT NULL
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id character varying NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    course_id character varying NOT NULL,
    name character varying NOT NULL,
    year_applied smallint NOT NULL,
    duration smallint NOT NULL,
    credits smallint NOT NULL,
    PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.enrolled_courses
(
    user_id character varying NOT NULL,
    course_id character varying NOT NULL
);

ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_user_roles FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_roles_user_roles FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrolled_courses
    ADD CONSTRAINT fk_user_enrolled_courses FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.enrolled_courses
    ADD CONSTRAINT fk_courses_enrolled_courses FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;